name: OpenSSF Scorecard Scan

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
